apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-limits
  namespace: app1
data:
  limits.conf: |
    limit_conn_zone $binary_remote_addr zone=perip_conn:10m;
    limit_req_zone  $binary_remote_addr zone=perip_req:10m rate=10r/s;

    #limit_conn perip_conn 5;                    # max 5 koneksi simultan per IP
    #limit_req  zone=perip_req burst=20 nodelay; # 10 rps/IP dengan burst 20

    server {
      listen 80;
      access_log /var/log/nginx/access.log;
      error_log  /var/log/nginx/error.log;

      limit_conn perip_conn 5;                     # max 5 koneksi simultan per-IP
      limit_req  zone=perip_req burst=20 nodelay;  # 10 rps/IP, burst 20

      add_header X-Sidecar "cafe-sidecar" always;

      location / {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header Connection "";
        #proxy_read_timeout 60s;

        proxy_pass http://127.0.0.1:8080;  # arahkan ke container app di pod yang sama
      }
    }
